Replaces JDK6 incompatible ConcurrentHashMap#keySet() call
ConcurrentHashMap#keySet() returns `KeySetView` in JDK8. This class is not present in JDK7 and causes `java.lang.NoSuchMethodError: com.hazelcast.enterprise.wan.PartitionWanEventQueueMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;` exceptions. keySet() is replaced with keys() call.