Suppress license expiration reminder task rejection when node is not running
When node fails to start, for example because of a validation failure during
Hot Restart, a redundant error log is printed. We can suppress this failure
if we detect that node is failed already.

Rejection stacktrace:
```
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@24f9c367 rejected from com.hazelcast.util.executor.LoggingScheduledExecutor@3ad913a7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@24f9c367 rejected from com.hazelcast.util.executor.LoggingScheduledExecutor@3ad913a7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[?:1.8.0_192]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) ~[?:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[?:1.8.0_192]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[?:1.8.0_192]
	at com.hazelcast.spi.impl.executionservice.impl.DelegatingTaskScheduler.schedule(DelegatingTaskScheduler.java:49) ~[classes/:?]
	at com.hazelcast.internal.util.LicenseExpirationReminderTask.scheduleWith(LicenseExpirationReminderTask.java:109) ~[classes/:?]
	at com.hazelcast.instance.EnterpriseNodeExtension.initLicenseExpReminder(EnterpriseNodeExtension.java:296) ~[classes/:?]
	at com.hazelcast.instance.EnterpriseNodeExtension.afterStart(EnterpriseNodeExtension.java:291) ~[classes/:?]
	at com.hazelcast.instance.Node.start(Node.java:423) ~[classes/:?]
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131) ~[classes/:?]
```